version: '3'

services:
  postgres-db:
    container_name: sendsms-postgres
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "SendSMS"
      TZ: "America/Sao_Paulo"
    ports:
      - "5432:5432"
    networks:
      - docker-network
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      TZ: "America/Sao_Paulo"
    ports:
      - "16543:80"
    depends_on:
      - postgres-db
    networks:
      - docker-network
    restart: always
  sendsms:
    container_name: sendsms-app
    image: sendsms-app
    build: .
    ports:
      - 8080:8080
    environment:
        - DATABASE_URL=jdbc:postgresql://postgres-db:5432/SendSMS
        - DATABASE_USERNAME=postgres
        - DATABASE_PASSWORD=postgres
    depends_on:
      - postgres-db
    networks:
      - docker-network
    deploy:
      resources:
        limits:
          memory: 700M
        reservations:
          memory: 700M
    restart: always



networks:
  docker-network:
    driver: bridge


